server:
    servlet: 
        context-path: /
    port: ${PORT:55325}

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB

storage:
    path: ${STORAGE_PATH:/}