server:
    servlet: 
        context-path: /
    port: ${PORT:55325}

    ssl:
        enabled: false
        key-alias: s4.ottimizzacontabil.com
        key-store: classpath:keystore/keystore.p12
        key-store-type: PKCS12
        key-password: ottimizza@123
        key-store-password: ottimizza@123

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB

storage:
    path: ${STORAGE_PATH:/}