buckets:
    
    - bussola-contabil:        
        name: bussola-contabil
        root: /buckets/ 
        auth_endpoint: https://ottimizza-oauth-server.herokuapp.com/oauth/check_token
        
    - tareffa-gestao-servicos:
        name: tareffa-gestao-servicos
        root: /buckets/ 
        auth_endpoint: https://ordemservicos.herokuapp.com/auth/check_token
        
    - zap-contabil:
        name: zap-contabil
        root: /buckets/
        auth_endpoint: https://zapcontabil.herokuapp.com/auth/check_token